AUB:
  distribution: chi2
  parameters:
    df: 15.9
    loc: -1.33
    scale: 7.4
CHL:
  distribution: chi2
  parameters:
    df: 8.65
    loc: 11.3
    scale: 7.78
CRO:
  distribution: chi2
  parameters:
    df: 3.62
    loc: 9.92
    scale: 12.3
DEF:
  distribution: lognorm
  parameters:
    loc: 0.7
    s: 0.368
    scale: 94.5
ETO:
  distribution: lognorm
  parameters:
    loc: -72.6
    s: 0.189
    scale: 216.0
GER:
  distribution: lognorm
  parameters:
    loc: -4.75
    s: 0.389
    scale: 93.1
LYO:
  distribution: lognorm
  parameters:
    loc: -23.3
    s: 0.284
    scale: 102.0
NAP:
  distribution: norm
  parameters:
    loc: 69.7
    scale: 36.6
NAT:
  distribution: rayleigh
  parameters:
    loc: 84.6
    scale: 38.7
NAU:
  distribution: cauchy
  parameters:
    loc: 88.3
    scale: 14.5
NAV:
  distribution: rayleigh
  parameters:
    loc: 35.0
    scale: 57.7
PEC:
  distribution: lognorm
  parameters:
    loc: 11.0
    s: 0.521
    scale: 44.9
RUE:
  distribution: lognorm
  parameters:
    loc: 9.23
    s: 0.524
    scale: 56.9
VES:
  distribution: gamma
  parameters:
    a: 1.66
    loc: 32.5
    scale: 29.0
VIN:
  distribution: cauchy
  parameters:
    loc: 64.4
    scale: 17.5
